name: modelling
on:
  pull_request:
  push:
   branches:
     - develop
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - name: Checking out of repo.
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Get npm cache directory
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install all node modules
        run: npm install

      - name: Test
        run: npm run test 

  deploy:
    name: Deploy the application
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop')
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Heroku
        run: heroku config:set GIT_HASH=${GITHUB_SHA} GIT_BRANCH=${GITHUB_REF} --app modellingapp-front

      - name: Push to Heroku
        run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/modellingapp-front.git $GITHUB_SHA:master


      